project_id = "lcmexcjgcjuawjkxfnqa"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.add-connection]
verify_jwt = false
